### ISSUE TITLE
About supplementary material in paper

### ISSUE THREAD

**Issue by wangtuo111** [lorenzovaquero/BUSCA#1]
Hello, I'm very interested in your research. I didn't find the supplementary materials mentioned in the paper that I downloaded from https://arxiv.org/abs/2407.10151. I would like to know how I can access these supplementary materials. Thank you.

**Comment by lorenzovaquero** [comment]
Hi, thanks a lot for your interest in our work!

Some other people have reported this and we have just updated the [arXiv version](https://arxiv.org/abs/2407.10151) to also include the supplementary material. You can find it at the end of the pdf (from page 20 onwards).

Best!
